# Generated by Django 3.1.5 on 2021-02-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='Wind',
            field=models.IntegerField(default=0),
        ),
    ]
