# Generated by Django 3.1.5 on 2021-02-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi_App', '0002_weather_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='Description',
            field=models.CharField(choices=[(0, 'Sunny'), (1, 'Rainy'), (2, 'Cloudy'), (3, 'Snow'), (5, 'Freezing'), (6, 'Broken clouds')], max_length=100),
        ),
    ]
